# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-08-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RnaSearch', '0002_auto_20200818_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chimpanzee_rnaedit',
            name='Cellline',
            field=models.CharField(max_length=200, verbose_name='Cellline'),
        ),
        migrations.AlterField(
            model_name='rhesus_rnaedit',
            name='Cellline',
            field=models.CharField(max_length=200, verbose_name='Cellline'),
        ),
    ]
